name: mca_project
description: "Nearzy - Hyperlocal Marketplace"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9
  carousel_slider: ^5.1.1
  google_fonts: ^8.2.1
  flutter_bloc: ^9.1.1
  http: ^1.6.0
  flutter_secure_storage: ^11.0.0
  geolocator: ^14.0.3
  flutter_native_splash: ^2.4.8
  connectivity_plus: ^7.3.1
  json_annotation: ^4.12.0
  image_picker: ^1.2.3
  flutter_spinkit: ^5.2.2
  geocoding: ^5.0.0
  lottie: ^3.5.1
  shimmer: ^4.0.0
  flutter_image_compress: ^2.5.1
  razorpay_flutter: ^1.4.0
  flutter_speed_dial: ^7.0.0
  infinite_scroll_pagination: ^5.1.1
  flutter_map: ^8.3.2
  latlong2: ^0.10.1
  url_launcher: ^6.3.2
  cached_network_image: ^4.0.0
  flutter_animate: ^4.5.2
  mobile_scanner: ^7.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.15.1
  json_serializable: ^6.14.1
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding/
    - assets/images/dummy_images/
    - assets/images/categories/
    - assets/images/featured_items/
    - assets/images/top_rated_shops/
    - assets/images/more_products/
    - assets/images/popular_shops/
    - assets/images/sale_offers/
    - assets/images/trending_now/
    - assets/images/top_picks/
    - assets/images/products_may_like/
    - assets/images/
    - assets/lottie/

flutter_native_splash:
  color: "#0F1A15"
  image: assets/images/splash_logo.png
  fullscreen: true
  android_12:
    image: assets/images/splash_logo_android12.png
    icon_background_color: "#0F1A15"
    color: "#0F1A15"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#0F1A15"
  adaptive_icon_foreground: "assets/images/splash_logo_android12.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#0F1A15"
    theme_color: "#0F1A15"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icon.png"
