spring.datasource.url=jdbc:postgresql://localhost:5432/localezy_db
spring.datasource.username=localezy_user
spring.datasource.password=localezy_pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.host.current=http://localhost:8080/